name = "mlnf"
compatibility_date = "2025-05-03"

[build]
command = "npm install && npm run build"
env = "production"

[build.upload]
format = "service-worker"
main = "index.html"

[site]
bucket = "."
entry-point = "index.html"
